### ISSUE TITLE
Unrecognized function or variable 'isaxes'

### ISSUE THREAD

**Issue by magdalenasabat** [JorritMontijn/zetatest#2]
Hi! Thanks for the library - excited to incorporate it into my analysis. 

I'm trying it out and I stumbled upon potential bugs/ missing dependencies. 

Here, first:

```
Unrecognized function or variable 'isaxes'.

Error in fixfig (line 22)
	if boolMakeActive && isaxes(handle)

Error in plotRaster (line 47)
	fixfig(gca);

Error in zetatest (line 264)
			plotRaster(vecSpikeTimes,vecEventStarts(:,1),dblUseMaxDur,10000);

Error in Script_zeta_select_neurons (line 134)
        [dblZetaP, vecLatencies,sZETA,sRate] = zetatest(vecSpikeTimes,matEventTimes,dblUseMaxDur,intResampNum , intResampNum,intPlot,intLatencyPeaks,boolDirectQuantile)
```
 
For now i use a simple workaround (inside `fixfig`)

```
    function isAxes = isaxes(handle)
        isAxes = ishghandle(handle,'axes');
    end
```
but maybe I'm missing some dependencies? I couldn't find any documentation on `isaxes`.

**Comment by JorritMontijn** [comment]
isaxes.m was indeed missing from the dependency folder, but it's added now if you update the repository
