### ISSUE TITLE
intZetaIdxRate can take 0 as a value

### ISSUE THREAD

**Issue by magdalenasabat** [JorritMontijn/zetatest#5]
Hi! 

`intZetaIdxRate  `is defined as `intZetaIdxRate = min(max(0,intZETALoc-1),numel(vecRate));` in line 346 of `zetatest.m` if `intZETALoc` takes a value of 1 `intZetaIdxRate` can take a value of 0, however in line 356  `intZetaIdxRate ` is used to index into `vecRate ` to extract latency values `vecLatencyVals = [vecRate(intZetaIdxRate) vecRate(intZetaIdxInvRate) vecRate(intPeakLoc) dblOnsetVal];` which causes it to throw an error

```
Error in zetatest (line 356)
				vecLatencyVals = [vecRate(intZetaIdxRate) vecRate(intZetaIdxInvRate) vecRate(intPeakLoc) dblOnsetVal];

Error in Script_zeta_select_neurons (line 125)
        [zeta(channel).dblZetaP,sZETA,~,zeta(channel).vecLatencies] = zetatest(vecSpikeTimes,matEventTimes,dblUseMaxDur,intResampNum
        ,intPlot,intLatencyPeaks,vecRestrictRange, boolDirectQuantile);
```

**Comment by JorritMontijn** [comment]
You're quite right, sorry about that! Translating the zetatest to python has made me a bit cross-eyed, and it seems I accidentally used 0-indexing here. Oops! It's fixed now.
