### ISSUE TITLE
getOnset doesn't correct if supplied peak is outside of supplied range

### ISSUE THREAD

**Issue by magdalenasabat** [JorritMontijn/zetatest#6]
Hi there,

I think this one is some weird rounding error. Basically  getOnset will throw a following error

```
Error using  <= 
Arrays have incompatible sizes for this operation.

Error in getOnset (line 52)
		intOnsetIdx = find(vecDataCropped <= dblThresh,1,'first');

Error in zetatest (line 355)
				[dblOnset,dblOnsetVal] = getOnset(vecRate,sRate.vecT,dblPeakTime,vecRestrictRange);

```

because dblThresh is empty. It is empty because the supplied dblPeakT in my case was 0.5 while the upper range was set to .5. This shouldn't have happened because gtPeak already removes peaks outside of window

```
	%remove peaks outside window
	indRemPeaks = vecT(vecLocsPos) < vecRestrictRange(1) | vecT(vecLocsPos) > vecRestrictRange(end);
	vecValsPos(indRemPeaks) = [];
	vecLocsPos(indRemPeaks) = [];
	vecPromsPos(indRemPeaks) = [];
```

I'm guessing it's some weird rounding error. Might make sense to restrict the variable type to avoid this kind of issues. What do you think? I might be missing soemthing. Please find below the spike vector as an example.

**Comment by magdalenasabat** [comment]
[example_chann.zip](https://github.com/JorritMontijn/zetatest/files/12477403/example_chann.zip)

**Comment by JorritMontijn** [comment]
Thanks for reporting all these bugs! I think we're getting there (fingers crossed)...

Anyway, getOnset should be fixed now. If the supplied peak is outside the restriction range, it will default to a new peak and display a warning.

**Comment by magdalenasabat** [comment]
Okay got it! Basically the check for peaks includes the restricted range (> not >=)  in `getPeak`, but in `getOnset` `intPeakT` in line 42 excludes it (indRemove again include it, then intPeakT excludes it  `intPeakT = find(vecCropT > dblPeakT,1,'first');`) solution would be to settle where to exclude or include (i guess  intPeakT = find(vecCropT >= dblPeakT,1,'first'); would make more sense)

```
%remove time points outside restricted range
	indRemove = vecT < vecRestrictRange(1) | vecT > vecRestrictRange(end);
	vecCropT = vecT(~indRemove);
	vecDataCropped = vecData(~indRemove);
	
	%find peak if none supplied
    if ~exist('dblPeakT','var') || isempty(dblPeakT) 
        [dblPeakVal,intPeakT] = max(vecDataCropped);
	    dblPeakT = vecT(intPeakIdx);
    else
        intPeakT = find(vecCropT > dblPeakT,1,'first');
    end
    dblPeakVal = vecDataCropped(intPeakT);
```

**Comment by magdalenasabat** [comment]
also, happy to contribute :)

**Comment by JorritMontijn** [comment]
The way it's written now, getPeak only returns peaks within the restricted range, but it still takes into account the entire data series to determine which peak is more "interesting" given the full data.

For example:
```
v=[0 2 0 10 1:10 12 9];
t=1:numel(v);
[dblPeakValue,dblPeakTime] = getPeak(v,t,[1 5])
```

returns:

```
dblPeakValue =

     0


dblPeakTime =

     3
```

In contrast,

`[dblPeakValue,dblPeakTime] = getPeak(v(1:5),t(1:5),[1 5])
`
returns:
```

dblPeakValue =

    10


dblPeakTime =

     4
```

Not sure if this helps clarifying why it's written the way it is, but I hope so;)

**Comment by JorritMontijn** [comment]
Oh, I just realized your point was about > instead of >=. Yes, I agree >= actually makes more sense, so that's updated now;)
