### ISSUE TITLE
unable to run zetatest on my own data

### ISSUE THREAD

**Issue by kingsEffy** [JorritMontijn/zetatest#8]
Hi Jorrit,
I'm trying to run zetatest on my own data, somthing simialr as Figure 7 in your eLife paper (https://www.biorxiv.org/content/biorxiv/early/2021/07/06/2020.09.24.311118/F7.large.jpg). The example data ran perfectly nothing went wrong. However, I kept failing on running my own data at section 'run the ZETA-test with specified parameters', seems my event timestamps not properly set? 
'
Error using repmat
Replication factors must be a row vector of integers or integer scalars.

Error in nanstd (line 62)
x = x - repmat(avg,tile);

Error in ttest (line 136)
sdpop = nanstd(x,[],dim);

Error in zetatest (line 249)
		[h,dblMeanP,ci,stats]=ttest(vecMu_Dur,vecMu_Pre);

Error in runExampleZETA (line 78)
[dblZetaP,sZETA,sRate,sLatencies] =
zetatest(vecSpikeTimes1,matEventTimes,dblUseMaxDur,intResampNum,intPlot,vecRestrictRange,boolDirectQuantile,dblJitterSize,boolStitch);

'
And, anything above this section ran nicely as well.

Is there any specific paramemetrs/requirements for matEventTimes? Apperantly my positional time tags aren't working here.

Thank you for buidling such amazing tools. Everything works in seconds on my machine uisng your sample data though.

best,
Effy

**Comment by kingsEffy** [comment]
Or any clues I can try out?

**Comment by JorritMontijn** [comment]
Hi Effy,

I think you have a custom nanstd.m function on your path, because the built-in version I have (R2019b) has no line 62. If you remove this file, it should probably work, but let me know if you're still having problems.

Best,
Jorrit
